const VERSION='2.0.0';
const KEY='levelUpProX_v2';
const defaults={settings:{business:'Level Up Property Renovation',phone:'07701 369715',email:'info@levelup-propertyrenovation.co.uk',overhead:10,profit:15},customers:[],quotes:[],jobs:[],invoices:[]};
let state=load();
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){return structuredClone(defaults)}}
function persist(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(Number(n)||0);const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===page));window.scrollTo(0,0)}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
function renderAll(){renderDashboard();renderCustomerDropdown();renderCustomers();renderQuotes();renderJobs();renderInvoices();loadSettings();calculateQuote();}
function newCustomer(){['customerId','customerName','customerPhone','customerEmail','customerAddress','customerNotes'].forEach(x=>$(x).value='')}
function saveCustomer(){let c={id:$('customerId').value||id(),name:$('customerName').value||'Unnamed customer',phone:$('customerPhone').value,email:$('customerEmail').value,address:$('customerAddress').value,notes:$('customerNotes').value};let i=state.customers.findIndex(x=>x.id===c.id);if(i>=0)state.customers[i]=c;else state.customers.push(c);newCustomer();persist()}
function editCustomer(cid){let c=state.customers.find(x=>x.id===cid);if(!c)return;go('customers');$('customerId').value=c.id;$('customerName').value=c.name;$('customerPhone').value=c.phone;$('customerEmail').value=c.email;$('customerAddress').value=c.address;$('customerNotes').value=c.notes}
function deleteCustomer(cid){if(confirm('Delete this customer?')){state.customers=state.customers.filter(c=>c.id!==cid);persist()}}
function renderCustomers(){let box=$('customersList');if(!state.customers.length){box.className='list empty';box.textContent='No customers saved yet.';return}box.className='list';box.innerHTML=state.customers.map(c=>`<div class="item"><div><strong>${c.name}</strong><small>${c.phone||''} ${c.email?'<br>'+c.email:''}<br>${c.address||''}</small></div><div><button onclick="editCustomer('${c.id}')">Edit</button> <button onclick="deleteCustomer('${c.id}')">Delete</button></div></div>`).join('')}
function renderCustomerDropdown(){let s=$('quoteCustomer');if(!s)return;s.innerHTML='<option value="">No customer selected</option>'+state.customers.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}
function newQuote(){['quoteId','projectAddress'].forEach(x=>$(x).value='');$('quoteNo').value='QU-'+new Date().getFullYear()+'-'+String(state.quotes.length+1).padStart(3,'0');$('quoteCustomer').value='';$('jobType').value='Single Storey Extension';$('length').value=3.5;$('width').value=3;$('rate').value=3200;$('vat').value=0;$('overhead').value=state.settings.overhead;$('profit').value=state.settings.profit;calculateQuote()}
function calcQuoteValues(){let area=(+$('length').value||0)*(+$('width').value||0),direct=area*(+$('rate').value||0),oh=direct*(+$('overhead').value||0)/100,prof=(direct+oh)*(+$('profit').value||0)/100,ex=direct+oh+prof,vat=ex*(+$('vat').value||0)/100,inc=ex+vat;return{area,direct,oh,prof,ex,vat,inc}}
function calculateQuote(){if(!$('length'))return;let v=calcQuoteValues();let cust=state.customers.find(c=>c.id===$('quoteCustomer').value);$('previewQuoteNo').textContent=$('quoteNo').value;$('previewCustomer').textContent=cust?cust.name:'—';$('previewProject').textContent=$('jobType').value;$('areaOut').textContent=v.area.toFixed(2)+' m²';$('exVatOut').textContent=money(v.ex);$('incVatOut').textContent=money(v.inc);$('previewScope').textContent=$('scope').value;$('previewExclusions').textContent=$('exclusions').value;$('breakdownBody').innerHTML=`<tr><td>Area</td><td>${v.area.toFixed(2)} m²</td></tr><tr><td>Direct Cost</td><td>${money(v.direct)}</td></tr><tr><td>Overheads</td><td>${money(v.oh)}</td></tr><tr><td>Profit</td><td>${money(v.prof)}</td></tr><tr><th>Total inc VAT</th><th>${money(v.inc)}</th></tr>`;$('paymentsBody').innerHTML=[['Deposit',10],['Foundations complete',20],['Walls to wall plate',20],['Roof watertight',20],['First fix & plastering',20],['Completion',10]].map(p=>`<tr><td>${p[0]}</td><td>${p[1]}%</td><td>${money(v.inc*p[1]/100)}</td></tr>`).join('')}
document.addEventListener('input',e=>{if(['length','width','rate','vat','overhead','profit','scope','exclusions','quoteNo','jobType','quoteCustomer'].includes(e.target.id))calculateQuote()});
function saveQuote(){calculateQuote();let v=calcQuoteValues();let q={id:$('quoteId').value||id(),quoteNo:$('quoteNo').value,customerId:$('quoteCustomer').value,address:$('projectAddress').value,jobType:$('jobType').value,length:+$('length').value,width:+$('width').value,rate:+$('rate').value,overhead:+$('overhead').value,profit:+$('profit').value,vat:+$('vat').value,scope:$('scope').value,exclusions:$('exclusions').value,total:v.inc,date:new Date().toLocaleDateString('en-GB'),status:'Quoted'};let i=state.quotes.findIndex(x=>x.id===q.id);if(i>=0)state.quotes[i]=q;else state.quotes.push(q);$('quoteId').value=q.id;persist();alert('Quote saved')}
function editQuote(qid){let q=state.quotes.find(x=>x.id===qid);if(!q)return;go('quotes');$('quoteId').value=q.id;$('quoteNo').value=q.quoteNo;$('quoteCustomer').value=q.customerId;$('projectAddress').value=q.address;$('jobType').value=q.jobType;$('length').value=q.length;$('width').value=q.width;$('rate').value=q.rate;$('overhead').value=q.overhead;$('profit').value=q.profit;$('vat').value=q.vat;$('scope').value=q.scope;$('exclusions').value=q.exclusions;calculateQuote()}
function deleteQuote(qid){if(confirm('Delete quote?')){state.quotes=state.quotes.filter(q=>q.id!==qid);persist()}}
function renderQuotes(){let box=$('quotesList');if(!state.quotes.length){box.className='list empty';box.textContent='No quotes saved yet.'}else{box.className='list';box.innerHTML=state.quotes.slice().reverse().map(q=>{let c=state.customers.find(x=>x.id===q.customerId);return`<div class="item"><div><strong>${q.quoteNo} — ${c?c.name:'No customer'}</strong><small>${q.jobType} | ${q.address||'No address'} | ${q.date}</small></div><div><span class="pill">${money(q.total)}</span><br><button onclick="editQuote('${q.id}')">Open</button> <button onclick="deleteQuote('${q.id}')">Delete</button></div></div>`}).join('')}let recent=$('recentQuotes');if(recent){if(!state.quotes.length){recent.className='list empty';recent.textContent='No quotes yet.'}else{recent.className='list';recent.innerHTML=state.quotes.slice(-3).reverse().map(q=>`<div class="item"><div><strong>${q.quoteNo}</strong><small>${q.jobType}</small></div><span class="pill">${money(q.total)}</span></div>`).join('')}}}
function printQuote(){calculateQuote();window.print()}
function newJob(){['jobId','jobName','jobStart','jobValue','jobNotes'].forEach(x=>$(x).value='');$('jobStatus').value='Lead'}
function saveJob(){let j={id:$('jobId').value||id(),name:$('jobName').value||'Unnamed job',status:$('jobStatus').value,start:$('jobStart').value,value:+$('jobValue').value||0,notes:$('jobNotes').value};let i=state.jobs.findIndex(x=>x.id===j.id);if(i>=0)state.jobs[i]=j;else state.jobs.push(j);newJob();persist()}
function editJob(jid){let j=state.jobs.find(x=>x.id===jid);if(!j)return;go('jobs');$('jobId').value=j.id;$('jobName').value=j.name;$('jobStatus').value=j.status;$('jobStart').value=j.start;$('jobValue').value=j.value;$('jobNotes').value=j.notes}
function renderJobs(){let box=$('jobsList');if(!state.jobs.length){box.className='list empty';box.textContent='No jobs saved yet.';return}box.className='list';box.innerHTML=state.jobs.map(j=>`<div class="item"><div><strong>${j.name}</strong><small>${j.status} | ${j.start||'No date'} | ${money(j.value)}</small></div><button onclick="editJob('${j.id}')">Open</button></div>`).join('')}
function newInvoice(){['invoiceId','invoiceCustomer','invoiceStage','invoiceAmount','invoiceDue'].forEach(x=>$(x).value='');$('invoiceNo').value='INV-'+new Date().getFullYear()+'-'+String(state.invoices.length+1).padStart(3,'0');$('invoicePaid').value='No'}
function saveInvoice(){let inv={id:$('invoiceId').value||id(),no:$('invoiceNo').value,customer:$('invoiceCustomer').value,stage:$('invoiceStage').value,amount:+$('invoiceAmount').value||0,due:$('invoiceDue').value,paid:$('invoicePaid').value};let i=state.invoices.findIndex(x=>x.id===inv.id);if(i>=0)state.invoices[i]=inv;else state.invoices.push(inv);newInvoice();persist()}
function renderInvoices(){let box=$('invoicesList');if(!state.invoices.length){box.className='list empty';box.textContent='No invoices saved yet.';return}box.className='list';box.innerHTML=state.invoices.map(inv=>`<div class="item"><div><strong>${inv.no} — ${inv.customer||'No customer'}</strong><small>${inv.stage} | Due ${inv.due||'—'} | ${inv.paid}</small></div><span class="pill">${money(inv.amount)}</span></div>`).join('')}
function renderDashboard(){if(!$('statQuotes'))return;$('statQuotes').textContent=money(state.quotes.reduce((s,q)=>s+(+q.total||0),0));$('statCustomers').textContent=state.customers.length;$('statJobs').textContent=state.jobs.filter(j=>j.status==='In Progress'||j.status==='Accepted').length;$('statInvoices').textContent=money(state.invoices.filter(i=>i.paid!=='Yes').reduce((s,i)=>s+(+i.amount||0),0))}
function calcMaterials(){let a=+$('matArea').value||0,t=+$('matThick').value||0,vol=a*t/1000;$('matResult').innerHTML=`Volume needed: <strong>${vol.toFixed(2)} m³</strong><br>Order allowance: <strong>${(vol*1.1).toFixed(2)} m³</strong><br>Rough 25kg cement bags for 4:1 screed: <strong>${Math.ceil(vol*8)}</strong>`}
function calcTiles(){let a=+$('tileArea').value||0,c=+$('tileCoverage').value||1;$('tileResult').innerHTML=`Adhesive bags: <strong>${Math.ceil(a/c)}</strong><br>Add waste allowance: <strong>${Math.ceil((a/c)*1.1)}</strong>`}
function loadSettings(){if(!$('settingBusiness'))return;$('settingBusiness').value=state.settings.business;$('settingPhone').value=state.settings.phone;$('settingEmail').value=state.settings.email;$('settingOverhead').value=state.settings.overhead;$('settingProfit').value=state.settings.profit}
function saveSettings(){state.settings={business:$('settingBusiness').value,phone:$('settingPhone').value,email:$('settingEmail').value,overhead:+$('settingOverhead').value||10,profit:+$('settingProfit').value||15};persist();alert('Settings saved')}
function clearAllData(){if(confirm('This clears saved customers, quotes, jobs and invoices on this device. Continue?')){localStorage.removeItem(KEY);state=load();renderAll()}}
if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js?v=2.0.0').then(reg=>{reg.update&&reg.update()}).catch(()=>{})}
window.addEventListener('load',()=>{newQuote();newInvoice();newJob();renderAll();calcMaterials();calcTiles();});
